# Generated by Django 4.1.3 on 2022-12-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_clienteestudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/datos/imagenes')),
            ],
            options={
                'verbose_name': 'estudio',
                'verbose_name_plural': 'estudios',
            },
        ),
    ]
